version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: achatina-nitrado
    ports:
      - "3002:3002"
    env_file:
      - .env
    networks:
      - achatina

networks:
  achatina:
    external: true